package sql;

public interface QueryInfo {
	String INSERT_CM = "INSERT INTO CUSTOMER (SSN, NAME, ADDRESS) VALUES(?, ?, ?)";
	String DELETE_CM = "DELETE FROM CUSTOMER WHERE SSN=?";
	String UPDATE_CM = "UPDATE CUSTOMER SET NAME=?, ADDRESS=? WHERE SSN=?";
	String SELECT_ALL = "SELECT SSN, NAME, ADDRESS FROM CUSTOMER";
}